security:
  providers:
    from_database:
      entity:
        class: App\Entity\Utilisateur
        property: mail

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: from_database
      form_login:
        login_path: login
        check_path: login
      logout:
        path: /logout
        target: /
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN] }
    - { path: ^/eleve, roles: [ROLE_ELEVE] }
    - { path: ^/examen, roles: [ROLE_MONITEUR, ROLE_SECRETAIRE, ROLE_ADMIN] }
    - { path: ^/moniteur, roles: [ROLE_MONITEUR, ROLE_ADMIN, ROLE_GERANT] }
    - { path: ^/secretaire, roles: [ROLE_SECRETAIRE, ROLE_ADMIN] }
    - { path: ^/gerant, roles: [ROLE_GERANT, ROLE_ADMIN] }
    - { path: ^/docusign/webhook/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/docusign/authorization_code/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


  encoders:
    App\Entity\Utilisateur: auto